development:
  adapter: mysql2
  encoding: utf8
  database: App42PaaS-Rails-MySQL-Sample_development
  pool: 5
  username: root
  password:

production:
  adapter: mysql2            
  host: 192.168.2.53                          # VM IP
  port: 64302                          # VM Port 
  database: t             # Database Name
username: a9ewwx3pyykl9pf5                 # User Name
  password: 'azbga84bmcjuut9zqk1g6jpme8mocx1i'                # Password

