development:
  adapter: mysql2
  encoding: utf8
  database: App42PaaS-Rails-MySQL-Sample_development
  pool: 5
  username: root
  password:

production:
  adapter: mysql2            
  host: 192.168.2.202                          # VM IP
  port: 38228                          # VM Port 
  database: t             # Database Name
  username: ayb7v9r9igni9cec                 # User Name
  password: 'a1a21dx6e1qzsex1eoh5bmu1e2hzzcpz'                # Password

