development:
  adapter: mysql2
  encoding: utf8
  database: App42PaaS-Rails-MySQL-Sample_development
  pool: 5
  username: root
  password:

production:
  adapter: mysql2            
  host: 172.16.2.167                          # VM IP
  port: 51341                          # VM Port 
  database: t             # Database Name
  username: apmn02lpya53ewvm                 # User Name
  password: 'ax8qkfxezxmgzpfpamurgwnp88nuzn95'                # Password

