development:
  adapter: mysql2
  encoding: utf8
  database: App42PaaS-Rails-MySQL-Sample_development
  pool: 5
  username: root
  password:

production:
  adapter: mysql2            
  host: 192.168.2.202                          # VM IP
  port: 62630                          # VM Port 
  database: t             # Database Name
  username: a131eaoiy1cs7b1q                 # User Name
  password: 'az9rx0sw4n2ve6mp1w5xr1flhwfuaom6'                # Password

