development:
  adapter: mysql2
  encoding: utf8
  database: App42PaaS-Rails-MySQL-Sample_development
  pool: 5
  username: root
  password:

production:
  adapter: mysql2            
  host: 172.16.2.167                          # VM IP
  port: 38923                          # VM Port 
  database: t             # Database Name
  username: a8z5d291jl3pdx2h                 # User Name
  password: 'wz4ntbx3n7urzd1ey9lbtvh5lfmgzq69'                # Password

