development:
  adapter: mysql2
  encoding: utf8
  database: App42PaaS-Rails-MySQL-Sample_development
  pool: 5
  username: root
  password:

production:
  adapter: mysql2            
  host: 172.16.2.167                          # VM IP
  port: 29250                          # VM Port 
  database: t             # Database Name
  username: aa9hqm12kttc70xx                 # User Name
  password: 'ai9m84ygtfx5flrib0ukorzwm31b9xk9'                # Password

