development:
  adapter: mysql2
  encoding: utf8
  database: App42PaaS-Rails-MySQL-Sample_development
  pool: 5
  username: root
  password:

production:
  adapter: mysql2            
  host: 192.168.2.202                          # VM IP
  port: 27789                          # VM Port 
  database: t             # Database Name
  username: awxaxk45pnlg4hn4                 # User Name
  password: 'a752ikezmhj0m2jk986smwc4du1q50n7'                # Password

