development:
  adapter: mysql2
  encoding: utf8
  database: App42PaaS-Rails-MySQL-Sample_development
  pool: 5
  username: root
  password:

production:
  adapter: mysql2            
  host: 192.168.2.202                          # VM IP
  port: 25581                          # VM Port 
  database: t             # Database Name
  username: a1aokbc2wqirudln                 # User Name
  password: 'ax1we0ltrh12x7vzqtc3nji0bvftvxly'                # Password

